#!/usr/bin/env bash
# Transfers a file from severi's client to another.
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.

# assigning parameters to variables
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
